# Surface7 managed: explicit camera activation only
# SPDX-License-Identifier: GPL-2.0-or-later
# blacklist handles aliases; install also blocks explicit legacy modprobe calls.
blacklist dw9719
install dw9719 /bin/false
blacklist ov5693
install ov5693 /bin/false
blacklist ov8865
install ov8865 /bin/false
blacklist ov7251
install ov7251 /bin/false
blacklist ipu_bridge
install ipu_bridge /bin/false
blacklist intel_ipu4p_isys_csslib
install intel_ipu4p_isys_csslib /bin/false
blacklist intel_ipu4p_psys_csslib
install intel_ipu4p_psys_csslib /bin/false
blacklist intel_ipu4p
install intel_ipu4p /bin/false
blacklist intel_ipu4p_psys
install intel_ipu4p_psys /bin/false
blacklist intel_ipu4p_isys
install intel_ipu4p_isys /bin/false
blacklist v4l2loopback
install v4l2loopback /bin/false
