# SPDX-License-Identifier: GPL-2.0-or-later
PACKAGE_NAME="surface7-ubuntu-frontcamera"
PACKAGE_VERSION="0.1.0"
AUTOINSTALL="yes"

BUILT_MODULE_NAME[0]="ov8865"
BUILT_MODULE_NAME[1]="dw9719"
BUILT_MODULE_NAME[2]="ipu-bridge"
BUILT_MODULE_NAME[3]="intel-ipu4p"
BUILT_MODULE_NAME[4]="intel-ipu4p-isys"
BUILT_MODULE_NAME[5]="intel-ipu4p-psys"
BUILT_MODULE_NAME[6]="intel-ipu4p-isys-csslib"
BUILT_MODULE_NAME[7]="intel-ipu4p-psys-csslib"
BUILT_MODULE_NAME[8]="v4l2loopback"

for index in 0 1 2 3 4 5 6 7 8; do
    BUILT_MODULE_LOCATION[$index]="."
    DEST_MODULE_LOCATION[$index]="/kernel/drivers/media"
done

MAKE[0]="bash ./scripts/dkms-build-modules.sh ${kernelver}"
CLEAN[0]="bash ./scripts/dkms-build-modules.sh clean ${kernelver}"
PRE_INSTALL="scripts/dkms-pre-install.sh ${kernelver}"
