monitor.libcamera.rules = [
  {
    matches = [
      {
        api.libcamera.sp7.profile = "hq"
      }
    ]
    actions = {
      update-props = {
        node.name        = "sp7.rear.hq"
        node.nick        = "Surface Rear HQ"
        node.description = "Surface Rear HQ"
      }
    }
  }
  {
    matches = [
      {
        api.libcamera.sp7.profile = "smooth"
      }
    ]
    actions = {
      update-props = {
        node.name        = "sp7.rear.standard"
        node.nick        = "Surface Rear Standard"
        node.description = "Surface Rear Standard"
      }
    }
  }
  {
    matches = [
      {
        api.libcamera.sp7.profile = "fast"
      }
    ]
    actions = {
      update-props = {
        node.name        = "sp7.rear.fast"
        node.nick        = "Surface Rear Fast"
        node.description = "Surface Rear Fast"
      }
    }
  }
  {
    matches = [
      {
        api.libcamera.sp7.profile = "front-standard"
      }
    ]
    actions = {
      update-props = {
        node.name        = "sp7.front.standard"
        node.nick        = "Surface Front Standard"
        node.description = "Surface Front Standard"
      }
    }
  }
  {
    matches = [
      {
        api.libcamera.sp7.profile = "front-hq"
      }
    ]
    actions = {
      update-props = {
        node.name        = "sp7.front.hq"
        node.nick        = "Surface Front HQ"
        node.description = "Surface Front HQ"
      }
    }
  }
]
